### ISSUE TITLE
Suggestion: use IoTHubTrigger instead of HttpTrigger for your tutorial

### ISSUE THREAD

**Issue by wickste** [Daniel-Krzyczkowski/WindowsIoTCore#1]
Daniel, nice job on the Motion Detector tutorial! I couldn't leave a comment on the blog post, so I am logging my small comment here as suggestion:

If you use an IoTHubTrigger for your Azure Function then you won't need to do the extra step of introducing an Azure Stream Analytics job, and the tutorial gets a bit more straight forward (unless you intend to use ASA for something else later down the road of course).

Cheers,
Stefan Wick

**Comment by Daniel-Krzyczkowski** [comment]
Hi Stefan,

Thank you so much for comment and for this insight! I will go through it and try to update my sample accordingly, good to know. :)

Greet,
Daniel

**Comment by wickste** [comment]
Btw, if you have trouble finding the documentation I won't be surprised :-). I am following up with the team to get this better documented. In the meantime I'll be happy to help with questions.

**Comment by Daniel-Krzyczkowski** [comment]
Thank you Stefan - good to know that there will be improvement in the documentation. :)
I will try to make changes this week and if I have any questions I will get back with them.
Once again, thank you!

**Comment by wickste** [comment]
Until we get a better official topic on docs.microsoft.com, you can take a look at this post. If it helps, please upvote :-)

https://stackoverflow.com/questions/52743156/azure-functions-how-to-set-up-iothubtrigger-for-my-iothub-messages/

**Comment by Daniel-Krzyczkowski** [comment]
Upvote completed, thanks! I will use it today and try to modify my sample :)
If there is anything else I can help, please let me know.

**Comment by Daniel-Krzyczkowski** [comment]
Stefan thank you once again for this - I updated my article and added IoTHubTrigger section:

https://github.com/Daniel-Krzyczkowski/Daniel-Krzyczkowski.github.io/blob/master/cloudyofthings/article1/index.md#azure-function-iothubtrigger

Cheers,
Daniel

**Comment by wickste** [comment]
Thanks - great work!
